### ISSUE TITLE
implement ACME challenge loopback test for http-01

### ISSUE THREAD

**Issue by coolaj86** [Daplie/le-challenge-webroot#2]
Just like there is a `set` and a `get` there ought to be a `loopback` which takes the same parameters as `set` and does everything necessary to test that it will pass the ACME challenge:

* [x] work with http-01
* [ ] ~~work with tls-sni-01~~ (the specs aren't actually similar)
* [ ] work on alternate ports
* [ ] fail on timeout >= 10 seconds

```javascript
  // note that for some strategies keyAuthorization may be null
  // however, for the sake of standardizing the implementation
  // without having to check parameter lengths, we'll always pass it in
, loopback: function (opts, domain, token, keyAuthorization, cb) {
    // TODO set a timeout for the failure case
    request('http://' + domain + '/.well-known/acme-challenge/' + token, function (err, resp) {
      if (keyAuthorization === resp.body) {
        cb(null, { loopback: true });
        return;
      }
      cb(new Error("did not pass http-01 loopback test"));
    });
  }
```

**Comment by insightfuls** [comment]
Can I question the value of this?

It seems like a nice idea, but there's so much that can go wrong that you simply can't test from the server:
- DNS could be improperly set up (and in complex setups, internal network DNS may be correct, but external DNS incorrect, so even if the server address were looked up, it could still go wrong).
- You also can't guarantee DNS has propagated to all the geographically diverse DNS servers Let's Encrypt uses to establish the IP.
- The server may be behind a firewall so it passes when tested locally, but fails externally.

There are also other complications: Let's Encrypt will always test http-01 on port 80 (tls-sni-01 is actually irrelevant here; it is a different type of challenge, now handled by `le-challenge-sni` or `le-challenge-hooks`, that runs on port 443). However, the local service `le-challenge-webroot` may be configuring may be running on a different port, and routing may not be in place to allow an external test from an internal network address.

It would also pull (indirectly) quite a lot of extra dependencies/code into this module, which may not be desirable.

In short, it seems to me that this is fraught with problems, and offers little benefit. The benefit seems to me to be limited to getting an error message a little sooner. The error is unlikely to be more informative, and may be less informative, or even misleading in some setups. The error may even be bogus, and prevent the ACME validation from being run even though it actually would succeed. I don't believe there is a significant rate limit on the number of challenges that can be sent, either (except to avoid DOS, I guess); there is only a rate limit on the number of certificates that can be issued (for QOS/to prevent abuse). So cutting down failed challenges isn't really a benefit anyway.

The best way to do an external test is simply to run the ACME validation.

To improve 'debugability', e.g. if ACME validation has failed and you're not sure why, perhaps another option would be to pause after setting the challenge, or have a set-only workflow, so that the user can manually examine and test the setup, before triggering the official ACME validation. IMHO it really is the sysadmin's job to check this, not the library's job.

Those are just some thoughts for consideration.

Thanks for the great software.

**Comment by insightfuls** [comment]
P.S. one reason I'm raising this is that I probably should add an issue to `le-challenge-sni` and/or `le-challenge-hooks` to do external tests too, if we want to move this way, as the warning triggering for this plugin is now also triggering for those, of course. But I'm not sure it's worth it.

**Comment by coolaj86** [comment]
My goal with this library is to make it as easy as possible for the most ignorant person to get https working.

Great sysadmins have been using https for years, but many of the newbies have been using https for about 6 months and only because letsencrypt has made it possible for them to do so.

I think we can add in an option `{ loopback: false }`, but I believe the default behavior should be a self-test because there are just so many areas where this can go wrong and I see a lot of issues from people where the error message from letsencrypt.org isn't helpful to them.

To your point: it may produce false positives, but it won't produce false negatives.

We don't have to worry about dependencies at all. All we need is node's native `http`, `https`, and `dns` modules.

I'll go ahead and actually implement the loopback in le-challenge-webroot with no deps today so that that warning goes away on my end.

**Comment by coolaj86** [comment]
With all of that said, I've given you equal access to the code and since you are taking an active role in contributing I'm not going to hang on so tightly to my ideals that I discourage future development. If after you go through the experience of writing the loopback you still feel very strongly about it and want to make the change, you're free to do so.

I have implemented it for [le-challenge-dns](https://github.com/Daplie/le-challenge-dns/blob/master/index.js#L154) as part of the tests and it was helpful to me to do so.

**Comment by insightfuls** [comment]
OK. I'll add to-dos to my modules regarding this, then.

I think false negatives will be possible in some circumstances, but they are probably more complicated setups, and their sysadmins should have more competence to realise what's going on and look for `loopback: false`.

**Comment by coolaj86** [comment]
I've got the loopback test implemented and tested here too now:

https://github.com/Daplie/le-challenge-webroot/blob/master/index.js#L72

**Comment by insightfuls** [comment]
The loopback implementation does not conform to the documented API, and thus does not silence the warnings. The documented signature is better (i.e. it would be best if this implementation conformed to it; don't change the API) because the tls-sni-01 uses hashes, so a verification can't proceed without the loopback method receiving the keyAuthorisation. This issue should probably be reopened, unless you want to create a new one.

**Comment by coolaj86** [comment]
If you pull on letsencrypt, the signature has been updated.

It requires two functions: `test` and `loopback`. `loopback` is the same as `get`, but external. `test` actually runs through the full gambit. I also found that something like `sni` will probably need to pass back something in the set callback.

**Comment by coolaj86** [comment]
The issue with the `set` callback can be seen in the example of `le-challenge-dns`.

**Comment by insightfuls** [comment]
> `loopback` is the same as `get`, but external.

This is not possible to implement for `tls-sni-01` (or `tls-sni-02`) so we may have a difficulty here. Actually, by the look of it, it isn't possible for `dns-01` either.

It's a little unclear what it should do. So far, the only strategy I've found which implements the `get` method is `le-challenge-memory`, and it's only consumed by the standalone server in `letsencrypt-cli`. I wonder whether `get` should be removed from the API and `le-challenge-memory` refactored. From what I can tell, in every other challenge strategy, the token is placed by `set` exactly where it needs to be to satisfy the challenge (including with manual, giving it to the user and giving them time to install it before returning). In `le-challenge-memory` the token isn't where it needs to be by return, but the standalone server queries for it later. I think it would make more sense for the standalone server to be considered an external service into which the challenge should be installed by the `set` method in `le-challenge-memory`, just like `le-challenge-dns` saves the token in an external service before `set` returns.

With this in mind, what should `loopback` return? Ordinarily a getter would return what was set by a setter, and you would assume this should pass:

```
set('foo','bar');
assert(get('foo') == 'bar');
```

`le-challenge-memory` only implements `get` at the moment, but it does match the criteria above. On the other hand, `le-challenge-dns` doesn't implement `get`, but implements `loopback`; however it returns not what was set (`keyAuthorization`) but a hash of it (`keyAuthDigest`), so the assertion above would fail.

You could just check for success or failure and not check the value retrieved, but that seems like a half-hearted test to me. And it would have to be documented in the API if that's the plan.

I notice you're now checking for the `test` method in `node-letsencrypt`. As far as I can tell, `test` is really only useful for strategy-internal tests (i.e. should not be consumed by `node-letsencrypt` itself), so I'm not sure it should be part of the plugin's public API and checked here.

What do you think?

**Comment by insightfuls** [comment]
Actually, I just thought of something else. I don't think `loopback` or `test` should be part of the plugin API at all.

Because how to test this externally has nothing to do with our storage mechanism for the challenge. All that is relevant is the challenge type.
- Every plugin that uses `http-01` will do an external test by making an HTTP request to `http://example.com/.well-known/acme-challenge/token` and should check the server returns `keyAuthorization`. This includes `le-challenge-webroot`, `le-challenge-manual`, and `le-challenge-memory` (as it's used with the standalone server for `http-01` challenges only)
- Every plugin that uses `tls-sni-01` will do an external test by making an SSL/TLS socket connection to the IP of `example.com` but using a server name of `token.acme.invalid` and should check the certificate presented by the server has the correct subject alternative names. This includes `le-challenge-sni` and `le-challenge-hooks`.
- Every `dns-01` plugin, like `le-challenge-ddns`, will perform the external test via a DNS query for a TXT record.

Why duplicate this external test code in every plugin that satisfies the same challenges? Why not just have the challenge plugins implement `set` and `remove` and have a test harness that does `set`, appropriate external test, signal the ACME server to validate, `remove`.

I still think removing `get` might be a good way forward as well. It doesn't really have a use, except for `le-challenge-memory` which I think indicates that plugin needs refactoring to match the API as implemented by all the others, rather than being a vote for keeping `get`.

**Comment by coolaj86** [comment]
I think you're right that the `loopback` method only needs to be implemented once per strategy.

The `test` method would still need to be implemented for each plugin, however, because it becomes dependent on the storage mechanism - i.e. `keyAuthorization` or `keyAuthDigest` needs to be calculated and stored and then tested as correct.

**Comment by coolaj86** [comment]
`get` is used here and it could be implemented for tls-sni-01 as well.

The idea being that get retrieves the value set by `set`. In the case of tls-sni, I believe you moved that logic into `le-auto-sni` by other means. I didn't look closely.

I'm not opposed to making `get` optional.

**Comment by insightfuls** [comment]
OK, I think that's sounding good.
- make `get` optional; perhaps check its signature if it does exist, but don't complain if it doesn't in `letsencrypt`; remove stub implementations
- no longer check for `loopback` in `letsencrypt`; instead, move the implementation from here to `letsencrypt`, and also from `le-challenge-ddns`, and supplement with one for `tls-sni-01`
- I believe `test` is module-local, i.e. it will only ever be used by `test.js` in the module, not from other modules; as such, it's not part of the public API, though it's good practice for module development; bottom line, we needn't check for it in `letsencrypt` either or even document it
The hardest part about these changes is adding the `tls-sni-01` loopback implementation, so perhaps I'll make these other changes alongside that, if you like.

**Comment by coolaj86** [comment]
It looks like the set parameter `keyAuthorization` should actually be replaced *before* the plugin gets it:

* http-01 - Key Authorization
* tls-sni-01 - `<<token>>.acme-challenge.invalid` certificate (?)
* dns-01 - Key Authorization Digest

**Comment by coolaj86** [comment]
That would break the plugin api... I'm wondering if there's a backwards-compat way to do this. Any ideas?

**Comment by insightfuls** [comment]
I actually like that the plugin API at the moment only provides the token and key authorisation to the plugin. It's really lightweight and gives the plugin the freedom to install it how it likes. E.g. in a cluster setup, it might be desirable to simply store the key authorisation in a central database and have the server software generate a cert or respond dynamically to DNS requests on the fly after consulting the database, rather than storing a cert and probably private key in the database. I avoided duplication of code that generates certs for `tls-sni-01` (and `tls-sni-02`) by putting it in a separate module (`le-tls-sni`). `dns-01` simply needs to compute a digest, which is hardly onerous. It fits nicely with the spec, too, which explains with each challenge type what to do with the token and key authorisation (but not how to generate the key authorisation).

I can see how it could be nice to provide a cert or digest to the plugin, too. I suppose a backward-compatible way to do it would be to allow the plugin to provide a different method, e.g. `install`, which would accept the cert or digest, ripe for installation, while plugins which want to do more work themselves could continue to implement `set` to simply get the key authorisation. `remove` is unaffected, `loopback` is to be implemented in core now, and `test` is not part of the public API anyway, so module developers can do what they like with it.

Speaking of which, I'm not sure how module owners would go about implementing `test`. I personally would probably just test that the cert I provided is returned by the server as expected, but others might prefer a full loopback test, and it could be convenient for them if they had access to the `loopback` implementation in core. We might like to consider exposing that somehow (perhaps as a method on `letsencrypt`).

**Comment by coolaj86** [comment]
@creationix is working on this and it's totally possible.

I do think that we need to bring `loopback` and `test` into `greenlock` directly, but as a "how it is right now" I'd like to add it to `le-challenge-sni`.

Testing it shouldn't be a problem as it's just
  * resolving the domain name to an ip address manually
  * making a tls connection to the server by the ip address
  * setting the sni to the acme.invalid
  * checking the certificate meta data

We already did this with the http-01 and dns-01 challenges:

* https://git.daplie.com/Daplie/le-challenge-webroot/blob/master/index.js#L72
* https://git.daplie.com/Daplie/le-challenge-ddns/blob/master/index.js#L164

**Comment by coolaj86** [comment]
The goal is to move `loopback` and `test` into `greenlock` proper because the details are not implementation specific - mainly it's just `set`, `get`, and `remove` that are implementation specific.

**Comment by coolaj86** [comment]
@insightfuls P.S. I added you to our greenlock team on npm. I think you already had publish access on the letsencrypt modules, but now you have publish access for the renamed greenlock modules too.
